//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeje.Model.Sys
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppDict
    {
        public string DictTypeKey { get; set; }
        public string DictTypeName { get; set; }
        public string DictKey { get; set; }
        public string DictName { get; set; }
        public Nullable<int> DictValue { get; set; }
        public Nullable<int> DictOrder { get; set; }
    }
}
