//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeje.Model.Sys
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SysEntities : DbContext
    {
        public SysEntities()
            : base("name=SysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AppDict> AppDicts { get; set; }
        public DbSet<AppLog4net> AppLog4net { get; set; }
        public DbSet<FileUploader> FileUploaders { get; set; }
        public DbSet<HrOrg> HrOrgs { get; set; }
        public DbSet<HrOrgHAuthority> HrOrgHAuthorities { get; set; }
        public DbSet<HrOrgHStaff> HrOrgHStaffs { get; set; }
        public DbSet<HrOrgVOrg> HrOrgVOrgs { get; set; }
        public DbSet<HrOrgVStaff> HrOrgVStaffs { get; set; }
        public DbSet<HrPosition> HrPositions { get; set; }
        public DbSet<HrPositionLevel> HrPositionLevels { get; set; }
        public DbSet<HrStaff> HrStaffs { get; set; }
        public DbSet<SysAuthority> SysAuthorities { get; set; }
        public DbSet<SysException> SysExceptions { get; set; }
        public DbSet<SysField> SysFields { get; set; }
        public DbSet<SysFunction> SysFunctions { get; set; }
        public DbSet<SysLog> SysLogs { get; set; }
        public DbSet<SysMenu> SysMenus { get; set; }
        public DbSet<SysOperation> SysOperations { get; set; }
        public DbSet<SysPerson> SysPersons { get; set; }
        public DbSet<SysRole> SysRoles { get; set; }
        public DbSet<SysRoleHAuthority> SysRoleHAuthorities { get; set; }
        public DbSet<SysRoleHUser> SysRoleHUsers { get; set; }
        public DbSet<SysUser> SysUsers { get; set; }
    }
}
