//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeje.Model.Sys
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysPerson
    {
        public SysPerson()
        {
            this.FileUploaders = new HashSet<FileUploader>();
            this.SysRoles = new HashSet<SysRole>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string MyName { get; set; }
        public string Password { get; set; }
        public string SurePassword { get; set; }
        public string MobilePhoneNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Village { get; set; }
        public string Address { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<decimal> Remark { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdatePerson { get; set; }
        public byte[] Version { get; set; }
    
        public virtual ICollection<FileUploader> FileUploaders { get; set; }
        public virtual ICollection<SysRole> SysRoles { get; set; }
    }
}
