//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeje.Model.Sys
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysUser
    {
        public SysUser()
        {
            this.SysRoleHUsers = new HashSet<SysRoleHUser>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string AddPerson { get; set; }
        public System.DateTime AddTime { get; set; }
        public string UpdatePerson { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string DeletePerson { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
    
        public virtual ICollection<SysRoleHUser> SysRoleHUsers { get; set; }
    }
}
