//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeje.Datas.Sys
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysOrg
    {
        public SysOrg()
        {
            this.SysRoleVOrg = new HashSet<SysRoleVOrg>();
        }
    
        public long Id { get; set; }
        public string OrgNo { get; set; }
        public string OrgName { get; set; }
        public string OrgTree { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdatePerson { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public bool IsClose { get; set; }
        public Nullable<System.DateTime> CloseTime { get; set; }
    
        public virtual ICollection<SysRoleVOrg> SysRoleVOrg { get; set; }
    }
}
