//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeje.Datas.Sys
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysPerson
    {
        public SysPerson()
        {
            this.SysRoleHPerson = new HashSet<SysRoleHPerson>();
            this.SysRoleVPerson = new HashSet<SysRoleVPerson>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string SurePassword { get; set; }
        public string TalentCode { get; set; }
        public string TalentName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdatePerson { get; set; }
        public bool IsClose { get; set; }
        public Nullable<System.DateTime> CloseTime { get; set; }
    
        public virtual ICollection<SysRoleHPerson> SysRoleHPerson { get; set; }
        public virtual ICollection<SysRoleVPerson> SysRoleVPerson { get; set; }
    }
}
