//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeje.Datas.Sys
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysRoleHOperation
    {
        public long Id { get; set; }
        public Nullable<long> SysRoleId { get; set; }
        public Nullable<long> SysMenuId { get; set; }
        public Nullable<long> SysOperationId { get; set; }
    
        public virtual SysMenu SysMenu { get; set; }
        public virtual SysOperation SysOperation { get; set; }
        public virtual SysRole SysRole { get; set; }
    }
}
