//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeje.Datas.Sys
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysRoleHPerson
    {
        public long Id { get; set; }
        public long SysPersonId { get; set; }
        public long SysRoleId { get; set; }
    
        public virtual SysPerson SysPerson { get; set; }
        public virtual SysRole SysRole { get; set; }
    }
}
